@@startuml
    actor customer #OrangeRed
    participant atm #red
    participant consortium #Blue
    participant bank #WhiteSmoke


    customer -> atm ++ : insert card

    atm -> consortium : verify card

    activate consortium
    
    consortium -> bank : verify account

    activate bank

    bank --> consortium: Account not ok 

    deactivate bank

    consortium --> atm: reject card

    deactivate consortium

    atm --> customer: eject card 

    deactivate atm   

@@enduml